### ISSUE TITLE
Add remote port in client config

### ISSUE THREAD

**Issue by 4eUeP** [4eUeP/language-server-network#1]
e.g.

Start the server with different images:

```
# for proj1
docker run ... myimage1 lsp-network-server --host 0.0.0.0 --port 3001

# for proj2
docker run ... myimage2 lsp-network-server --host 0.0.0.0 --port 3002
```

And client config:

```
- root: /proj1
  port: 3001
  command: ccls
  args:
    - '--init={"client": {"snippetSupport": false}, "completion": {"placeholder": false}}'

- root: /proj2
    port: 3002
  command: ccls
  args:
    - '--init={"client": {"snippetSupport": false}, "completion": {"placeholder": false}}'
```
